### ISSUE TITLE
Support existing RabbitMQ queues

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-producer#10]
See https://github.com/Senzing/stream-loader/issues/87

**Comment by jeffadair** [comment]
We have some competing interests here. We need to make it easy to connect to existing exchanges and queues. But we also want our examples to be as simple and easy to run as possible.

So here is how I propose to approach this. I've added a new parameter to stream-producer (and eventually to stream-loader) named "SENZING_RABBITMQ_USE_PREEXISTING_EXCHANGE_AND_QUEUE". 

When that is true, we will use the "passive" declare of the rabbitmq exchange/queue_declare() calls. A passive declare only looks for an existing exchange/queue with the passed name. It ignores any other passed parameters and just use the exchange/queue as is. Just like we want.

When that is false, it will attempt to connect to/create a direct exchange and traditional queue with a routing key of '' (empty string). This is the brain-dead simple configuration we want for our examples. We are not trying to support anything else. (This is slightly different that what it was doing before, but the same outcome)

For stream-loader SENZING_RABBITMQ_USE_PREEXISTING_EXCHANGE_AND_QUEUE will default to true, as we expect users to use stream-loader in their application and will have preconfigured and tuned exchanges/queues

for stream-producer SENZING_RABBITMQ_USE_PREEXISTING_EXCHANGE_AND_QUEUE will default to false, as that is intended mostly as an example of how to load records to the queue of your choice. If it works for them long term, they can switch it over if they need to.

stream-loader's default behavior will change since it now creates a queue (and indirectly an exchange) with no option to connect to an existing queue.

@docktermj @brianmacy

**Comment by docktermj** [comment]
That design work for me.  Thanks, @jeffadair!

**Comment by jeffadair** [comment]
SENZING_RABBITMQ_USE_PREEXISTING_EXCHANGE_AND_QUEUE was changed to be SENZING_RABBITMQ_USE_EXISTING_ENTITIES as 'Entities' in rabbitMQ cover exchanges, queues, and mappings
